### ISSUE TITLE
packages for redhat/centos

### ISSUE THREAD

**Issue by JensTimmerman** [dmaes/ansible-role-bitwardenrs#4]
following packages need to be installed when run on centos8:

```
_bitwardenrs_build_packages:
  - gcc
  - openssl-devel
  - pkg-config
  - tar
```

I would create a pr for this, however I'm not really sure how to load these vars inside the vars/main.yml file

**Comment by dmaes** [comment]
Great thanks, I will add them.

**Comment by dmaes** [comment]
Currently don't have a centos machine at hand, so if you could confirm if it works?

**Comment by JensTimmerman** [comment]
I needed to make sure root was in the sudoers file, without that I got an error about root not being in the sudoers file, but that might be more related to my ansible setup then this role.

The correct vars file seems to be picked up
```
TASK [ansible-role-bitwardenrs : Gather OS-specific variables] ***************************************************************************************************************************************************************************************************************************
ok: [bitwardendev] => (item=/root/.ansible/roles/ansible-role-bitwardenrs/vars/redhat.yml)
```

Then I  also get a warning 
```
TASK [ansible-role-bitwardenrs : Install rust nightly] ***********************************************************************************************************************************************************************************************************************************
[WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running su
```

But current master works on my CentOs8 system, thanks for this quick fix!

btw, looking at your role I believe tar might also be needed on Debian, but I suspect it is available by default? I'm a bit surprised dnf works on centos without tar present ;)

**Comment by dmaes** [comment]
Yeah, need to work on that warning. It's not as simple as just doing `become_user: bitwardenrs` because https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user . I fixed it in an other project, just need some time to look at it.

And IIRC tar is indeed available by default in debian
